#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     Left,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Right,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     LinearSlide,   tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     Arm,           tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    ArmExtend,            tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C3_2,    ArmRotation,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

string programs[] = {"Text 1", "Text 2", "Text 3", "Text 4"};
int i = 0;

void menu(){
	i = 0;
	nxtDisplayCenteredTextLine(0, "Select program.");
	while(1){
		nxtDisplayCenteredTextLine(3, "%s", programs[i]);
		if(nNxtButtonPressed == 1){
			if(i+1 < (sizeof(programs) / sizeof(programs[0]))){i++;}
			else{i = 0;}
			wait1Msec(500);
		}
		if(nNxtButtonPressed == 2){
			if(i != 0){i--;}
			else{i = sizeof(programs) / sizeof(programs[0]) - 1;}
			wait1Msec(500);
		}
		if(nNxtButtonPressed == 3){
			eraseDisplay();
			nxtDisplayCenteredTextLine(1, "Selected");
			nxtDisplayCenteredTextLine(2, "program:");
			nxtDisplayCenteredTextLine(3, "%s", programs[i]);
			wait1Msec(3000);
			break;
		}
	}
}

task main()
{
	menu();
}
